### PR TITLE
Update active_working_groups.Rmd

### PR DESCRIPTION
**Pull request by jananiravi**
@aedin @lshep @stephaniehicks & others -- anything to add to the R-Ladies working group?

### CODE REVIEW

**Review by jananiravi — COMMENTED** [review]
@lshep could you check and approve/merge?

**Review by lshep — APPROVED** [review]

**Comment by lshep** [comment]
I'm not sure why but it isn't giving me the option to merge and is waiting for a check to complete

**Comment by jananiravi** [comment]
Is it because I had requested your review/approval?
________________________________

**Comment by lshep** [comment]
No because I approved it and it still is pending

**Comment by jananiravi** [comment]
@lshep any chance I could request write access to this repo? Unable to merge. thanks!

**Comment by lshep** [comment]
I think you can't merge because there are conflicts see the message above and because of some issue with the precheck but yes I'll give you write access

**Comment by lshep** [comment]
Made a different PR to add this since your PR wouldn't pass the pre-checks from conflicts.

**Pull request closed without merging**
